apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: ironcore864/hello:latest
        ports: 
        - containerPort: 3000 
