{{- if eq .Values.database.migrationStrategy "job" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-db-setup"
  labels:
{{ include "gorgeous-code-assessment.labels" . | indent 4 }}
spec:
  template:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      containers:
        - name: "{{ .Chart.Name }}-db-setup"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - 'rake db:exists && rake db:migrate || rake db:setup'
          env:
            - name: RAILS_ENV
              value: {{ .Values.application.environment }}
            - name: POSTGRES_PASSWORD # Avoids failure doe to the trailing char
              # Ref: https://github.com/docker-library/postgres/issues/308#issuecomment-371587622
              valueFrom:
                secretKeyRef:
                  name: {{ include "gorgeous-code-assessment.postgresql.fullname" . }}
                  key: postgresql-password
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: database-credentials
              mountPath: "{{ .Values.workDir }}/config/database.yml"
              readOnly: true
              subPath: database.yml
            - name: devise-key
              mountPath: "{{ .Values.workDir }}/config/initializers/devise.rb"
              readOnly: true
              subPath: devise.rb

      volumes:
        - name: database-credentials
          secret:
            secretName: "{{ .Release.Name }}-database-credentials"
        - name: devise-key
          secret:
            secretName: "{{ .Release.Name }}-devise-key"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
