apiVersion: v1
kind: Service
metadata:
  name: {{ include "gorgeous-code-assessment.fullname" . }}
  labels:
{{ include "gorgeous-code-assessment.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "gorgeous-code-assessment.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
