default: &default
  adapter: postgresql
  host: <%= ENV['POSTGRES_HOST'] %> 
  endcoding: utf8
  pool: 5
  timeout: 5000
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASS'] %> 

development:
  <<: *default
  database: gorgeous-code_development

test:
  <<: *default
  database: gorgeous-code_test

production:
  <<: *default
  database: gorgeous-code_production
