default: &default
  adapter: postgresql
  host: postgresdb
  endcoding: utf8
  pool: 5
  timeout: 5000
  username: 'postgres'
  password: 'mysecretpassword'

development:
  <<: *default
  database: gorgeous-code_development

test:
  <<: *default
  database: gorgeous-code_test

production:
  <<: *default
  database: gorgeous-code_production
