apiVersion: v1
kind: Service
metadata:
  name: {{ include "testapp.fullname" . }}
  namespace: {{ .Values.environment }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "testapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
